### ISSUE TITLE
../../assets/filetypes: File does not exist

### ISSUE THREAD

**Issue by probonopd** [yatima1460/Drill#11]
**Linux distro**

Ubuntu 18.04

**Runtime type**

ELF

**Describe the bug**

```
me@host:~$ Downloads/DrillGTK.elf 
std.file.FileException@std/file.d(3843): ../../assets/filetypes: File does not exist
----------------
??:? ref @safe std.file.DirEntry std.file.DirEntry.__ctor(immutable(char)[]) [0x5643fc4b820d]
??:? Drill.Window.DrillWindow Drill.Window.DrillWindow.__ctor(gtk.Application.Application) [0x5643fc2978da]
??:? void Main.main(immutable(char)[][]).__dgliteral2(gio.Application.Application) [0x5643fc2963b3]
??:? extern (C) void gobject.DClosure.DClosure.d_closure_marshal!(void delegate(gio.Application.Application)).d_closure_marshal(gobject.c.types.GClosure*, gobject.c.types.GValue*, uint, gobject.c.types.GValue*, void*, void*) [0x5643fc38ad55]
??:? g_closure_invoke [0x7f82dbc16f6c]
```

**Comment by yatima1460** [comment]
oh yes ahah, the .elf type is just a built binary, mainly for debug purposes, technically when you build a GUI version like DrillGTK it will search for assets in the upper folders

With the AppImage I will bundle the assets inside!

**Comment by yatima1460** [comment]
if you clone the repo and put DrillGTK.elf inside /source/drillgtk it should run

**Comment by yatima1460** [comment]
I wonder if I should make the D compiler output the binary in the root folder, so even the .elf can run cleanly with the assets folder, but the AppImage is coming soon anyway

**Comment by yatima1460** [comment]
AppImage fixed this

https://github.com/yatima1460/Drill/releases/download/1.0.0rc2/Drill-x64.AppImage

**Comment by probonopd** [comment]
Cool, it is working for me on Xubuntu 18.04.
