### ISSUE TITLE
Not showing files indexed, files blocked etc.

### ISSUE THREAD

**Issue by RustyRaptor** [yatima1460/Drill#13]
**Linux distro**
Kubuntu 18.04

**Runtime type**
Debug mode

**Describe the bug**
in the status bar at the bottom it isn't displaying anything just question marks. 

**To Reproduce**
1. Install and run Drill using instructions in README for debug x64-GTK

**Expected behavior**
Should show number of indexed files etc. 

**Screenshots**
![Screenshot_20190512_103148](https://user-images.githubusercontent.com/7911442/57585167-93382e00-74a1-11e9-9d24-b27295ec4a83.png)
![Screenshot_20190512_103329](https://user-images.githubusercontent.com/7911442/57585169-97644b80-74a1-11e9-8179-43270523ca87.png)

**Comment by yatima1460** [comment]
This is gonna change with the next version

The Release version will have a clean UI
The Debug version will list all stuff in the bottom status bar and some labels will be half done/broken but we don't care about them because it's the debug version anyway!

**Comment by yatima1460** [comment]
Btw this is the result of splitting Drill into Core and GTK so some labels aren't connected yet
