### ISSUE TITLE
Ty Coon, President of Vice

### ISSUE THREAD

**Issue by TyCoonOfficial** [yatima1460/Drill#18]
Dear developer of Drill. You left an unmodified GNU General Public License in your software. It is now version 1.0.0 and many people have agreed to the terms of the license. 

I, Ty Coon, have returned to now hereby lay claim as President of Vice as lord and master over this project, and all those who have agreed to the terms of the agreement, post haste and hitherto.

**Comment by yatima1460** [comment]
10/10 issue
