### ISSUE TITLE
Drill fails if it encounters a broken link

### ISSUE THREAD

**Issue by famellad** [yatima1460/Drill#2]
**Description**
The program fails spectacularly when it encounters a broken link, in all fairness, this is great for finding broken links

**To Reproduce**
1. Create a file link
2. Delete the file, but not the link
3. Watch drill crash and burn

**Expected behavior**
The broken link should be ignored

**Screenshots**
![image](https://user-images.githubusercontent.com/1228894/57068530-f7881000-6c9f-11e9-8f87-ff87741f6ef1.png)

**Desktop:**
 - Antergos (linux 5.0.1)

**Comment by yatima1460** [comment]
`os.follow_symlinks = False` and mount points are iterated using psutil, this should not happen anymore, let me know

**Comment by yatima1460** [comment]
also it needs a discussion if to set `os.follow_symlinks = False` or not

**Comment by v0idpwn** [comment]
well it should not break even with following symlinks enabled

**Comment by RustyRaptor** [comment]
if following symlinks is enabled we should have a function limit the depth of it.

**Comment by yatima1460** [comment]
following symlinks is ok, the problem is how to prevent loops

maybe distinguish files using the inode number?

**Comment by yatima1460** [comment]
but I wonder if following symlinks is important to find user data

**Comment by yatima1460** [comment]
mount points are never symlinks right?

**Comment by RustyRaptor** [comment]
No they aren't. Hasn't stopped people from trying though apparently. 

https://unix.stackexchange.com/questions/49014/using-a-symlink-for-a-mountpoint

**Comment by yatima1460** [comment]
Switched to D and rewritten the crawling system, let me know if this still happens

**Comment by yatima1460** [comment]
Tested with 1.0.0, can confirm it's fixed
