### ISSUE TITLE
Software name collision

### ISSUE THREAD

**Issue by Mel34** [yatima1460/Drill#21]
Just to let you know, there already exists a program in GNU world called **drill** authored by Jelte Jansen and Miek Gieben. It's been around since at least 2004.

By using word 'drill' as a name for your project you are creating a name collision. I understand that this is a very new project and in the interest of community I urge you to reconsider the name.

**Comment by yatima1460** [comment]
Is it correct to assume that just changing the binary name in /usr/bin and the folder name in opt will fix collisions?

**Comment by Mel34** [comment]
Yeah, software can be packaged under a different name. E.g. drillsearch instead of drill.

**Comment by yatima1460** [comment]
fixed, renamed to "drill-search"

**Comment by yatima1460** [comment]
https://github.com/yatima1460/Drill/releases/tag/1.133
