### ISSUE TITLE
It assumes a /media directory exists

### ISSUE THREAD

**Issue by famellad** [yatima1460/drill#3]
**Description**
Related to #2, it just plain assumes /media exists, and when it doesn't it throws an error.

**To Reproduce**
1. Don't have /media
2. That's it

**Expected behavior**
Literally anything but a crash

**Screenshots**
![image](https://user-images.githubusercontent.com/1228894/57068861-f2779080-6ca0-11e9-9432-0e385aad3fb7.png)

**Desktop (please complete the following information):**
- Antergos (Linux 5.0.1)

**Comment by yatima1460** [comment]
This will be fixed soon when I will use the mounts list from /proc

**Comment by yatima1460** [comment]
fixed
