### ISSUE TITLE
Travis builds 2 times

### ISSUE THREAD

**Issue by yatima1460** [yatima1460/Drill#30]
https://travis-ci.org/yatima1460/Drill/builds

Ideas why?

**Comment by RustyRaptor** [comment]
What are the cron job settings?

**Comment by yatima1460** [comment]
I have no cron jobs set

**Comment by yatima1460** [comment]
It seems it's a Travis misbehavior, it first builds because of a commit and then builds again because Travis itself added its own tag branch

**Comment by yatima1460** [comment]
Do you recommend building using cron jobs instead of commits?

**Comment by RustyRaptor** [comment]
I would say so yeah. Just have a daily build. If you want you can do monthly or weekly stable releases as well by just making a new branch. You can make one cron job per branch.

**Comment by yatima1460** [comment]
fixed with adding:

```yaml
branches:
  only:
  - master
```
