### ISSUE TITLE
CLI access in the deb release? 

### ISSUE THREAD

**Issue by RustyRaptor** [yatima1460/Drill#32]
**Is your feature request related to a problem? Please describe.**
There is only a gtk version for the deb release. 

**Describe the solution you'd like**
Wouldn't it make sense to package a binary for the cli with the same deb? 

**Describe alternatives you've considered**
I guess you could just build a seperate deb for the cli or something. 

**Additional context**
I would love to be able to easily install the cli to the system that way I can integrate drill with some of my apps and scripts.

**Comment by yatima1460** [comment]
A separate .deb is better because some users would like to install only the CLI in a server that doesn't have graphical interfaces so GTK can't be installed

**Comment by RustyRaptor** [comment]
Makes sense. That's what projects like transmission (torrent client) do too come to think of it.

**Comment by yatima1460** [comment]
https://github.com/yatima1460/Drill/releases/tag/1.183

**Comment by yatima1460** [comment]
"drill-search-cli" to start the interactive search

or: drill-search-cli "filename" to search instantly
