### ISSUE TITLE
drill-search should follow POSIX standards

### ISSUE THREAD

**Issue by v0idpwn** [yatima1460/Drill#39]
**Is your feature request related to a problem? Please describe.**
drill-search feels limited and has no options support

**Describe the solution you'd like**
use std.getopt to receive and parse arguments

**Describe alternatives you've considered**
manual argument parsing, like the way it works now

**Comment by v0idpwn** [comment]
I'm willing to rewrite the CLI entirely, but apparently there aren't so many options even on drill-ui now. 
What options should it have?

**Comment by yatima1460** [comment]
As you can imagine the CLI version is not my priority but if you can add cool arguments to it then even better!

This is the near future:

the UI version will be renamed to drill-search-gtk and placed inside /usr/bin
the CLI version will be renamed just drill-search

the UI version will be arguments-less, easy to use for the average user, just click on the icon and it's ready

the CLI version should only have arguments related to how the CLI should output the data found

any other arguments that are about the crawling itself like "--no-blocklist" should be implemented in the core and itself and this will be added somewhere in the future

**Comment by v0idpwn** [comment]
Agreed.
What are the drill-core options in the roadmap?

**Comment by yatima1460** [comment]
--crawl-everything
--root-folder
specifies a root folder to search in like it was the only mounted disk
--singlethread
--stop-first
stops after first result found

and any other ideas welcome

**Comment by v0idpwn** [comment]
--no-symlinks ?

**Comment by yatima1460** [comment]
Drill already ignores symlinks because following them is useless and will only bring pain

You could end up in another disk making multithreading useless
