### ISSUE TITLE
psutilcheck not defined?

### ISSUE THREAD

**Issue by KowalskiThomas** [yatima1460/drill#4]
**Describe the bug**
When starting drill with `python3 drill.py`, I get the following error:

```
  File "drill.py", line 519
    global psutilcheck
    ^
SyntaxError: name 'psutilcheck' is used prior to global declaration
```

**To Reproduce**
1. Start drill 

**Desktop (please complete the following information):**
 - OS: elementaryOS 5.0 Juno
 - Python 3.6.7

**Additional context**
I just cloed the repository and launched the script.

**Comment by yatima1460** [comment]
psutil is now needed to grab a list of real mount points, fixed by removing the check
