### ISSUE TITLE
The program doesn't run when using the fish terminal

### ISSUE THREAD

**Issue by gabdub** [yatima1460/Drill#44]
**Linux distro**
Ubuntu Mate 19.04

**Build Version**
Drill-ui-linux-1.199-x86_64.deb

**Describe the bug**
The program doesn't run when using the **fish** terminal.
The file "/usr/bin/drill-search" doesn't have "#!/bin/bash" in the first line.

**Other notes**
 "$1" is missing in Drill/build.bash line 353 (...DEBFILE/usr/bin/$DEB_PACKAGE_NAME)
```
# install binary redirect for /usr/bin and set it executable
    mkdir -p DEBFILE/"$1"/usr/bin
    echo    #!/bin/bash                                     >  DEBFILE/usr/bin/$DEB_PACKAGE_NAME
    echo    /opt/$DEB_PACKAGE_NAME/"$EXECUTABLE_IN_OPT" "\$@" >> DEBFILE/"$1"/usr/bin/$DEB_PACKAGE_NAME
chmod +x DEBFILE/"$1"/usr/bin/$DEB_PACKAGE_NAME
```

**Comment by yatima1460** [comment]
I knew I couldn't trust

` echo    #!/bin/bash                                     >  DEBFILE/usr/bin/$DEB_PACKAGE_NAME`

**Comment by gabdub** [comment]
Nice. That was fast!

**Comment by yatima1460** [comment]
don't close the issue, until I commit a fix, so I don't forget!

**Comment by yatima1460** [comment]
I actually searched around and couldn't find a way to escape "#"

I think I will just include the bin/script as a real file and not generate it with echo

**Comment by gabdub** [comment]
Have you tried something like this?

`echo -e '\x23'`

**Comment by yatima1460** [comment]
you are the absolute madman, it works

**Comment by RustyRaptor** [comment]
fsh
