### ISSUE TITLE
new AUR package

### ISSUE THREAD

**Issue by simonbcn** [yatima1460/Drill#45]
I've created a new AUR package of UI version, the previous has vanished, based on stable .deb version: https://aur.archlinux.org/packages/drill-search/

**Comment by yatima1460** [comment]
thanks, website updated

**Comment by simonbcn** [comment]
Sorry, the name of the package created is incorrect according to Arch Linux standards, I have created a new one with the correct name: https://aur.archlinux.org/packages/drill-search-bin/

**Comment by yatima1460** [comment]
website updated

**Comment by yatima1460** [comment]
I installed Arch myself and found that Drill would not scan secondary mounted drives

latest version fixes it, tell me how I can update the AUR, or if you can do it yourself, thanks
also I will rename drill-ui to drill-gtk
also I would like to add the cli version too to AUR

https://github.com/yatima1460/Drill/releases/tag/1.208

**Comment by yatima1460** [comment]
I created an account on AUR called `yatima1460`

**Comment by simonbcn** [comment]
ok, I will create 2 packages: drill-gtk-bin and drill-cli-bin with the latest versions released. I will then request the removal of the current package. I'll let you know when I'm ready.
Unless you want to do it yourself.

**Comment by simonbcn** [comment]
I think the AUR package names should be better: `drill-search-gtk-bin` and `drill-search-cli-bin`.

**Comment by simonbcn** [comment]
Packages created: https://aur.archlinux.org/packages/drill-search-gtk-bin/ and https://aur.archlinux.org/packages/drill-search-cli-bin/
I'm going to request to delete the previous AUR: drill-search-bin

**Comment by simonbcn** [comment]
Please, notify me when you change the names of releases.

**Comment by yatima1460** [comment]
website updated with those links;

I am not closing the issue because "ui" will be renamed to "gtk"

the reason is because I will have more than one frontend, on Windows it's better to use WinAPI and on OSX Cocoa

**Comment by yatima1460** [comment]
@simonbcn I updated everything, the project directories tree structure, the build system and the website now fetch all the downloads automatically from GitHub Releases

When you can update the AUR!

**Comment by simonbcn** [comment]
Done!

**Comment by yatima1460** [comment]
@simonbcn what do you think about adding a non-bin version that actually builds from source?
it's pretty easy

you first install DUB and DMD as backend compiler and then cd Source/Frontend/GTK and dub build -b release

**Comment by yochananmarqos** [comment]
> what do you think about adding a non-bin version that actually builds from source?
> it's pretty easy
> 
@yatima1460 I just created one, but the binary can't find the Assets folder, I'm stumped. Here's the [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/tree/master/drill-search).

**Comment by simonbcn** [comment]
What is the difference between an AUR package that installs from a done compilation (_in this case, extracted from .deb package_) and one that compiles from the source?
I would understand the usefulness of a `-git` package that compiles the master version but one that installs the same as the bin version. :question:

**Comment by yochananmarqos** [comment]
It's better to build from source when possible rather than use precompiled binaries. A precompiled binary may look for older libraries than are installed on the system and cause incompatibilities.

**Comment by simonbcn** [comment]
@yochananmarqos yes, you're right.

@yatima1460 I have requested the deletion of my `...-bin` packages as they are unnecessary having those of him.
