### ISSUE TITLE
Allow close window with one keystroke

### ISSUE THREAD

**Issue by simonbcn** [yatima1460/Drill#46]
It would be very comfortable and quick to close the window with a single keystroke: for example ESC.

**Comment by yatima1460** [comment]
Already in the TODOs 😁

It's technically so simple that if you want to do a pull request I would accept it instantly

![image](https://user-images.githubusercontent.com/7545597/58742887-2244c000-8428-11e9-97b9-c7a58def8ad3.png)

**Comment by yatima1460** [comment]
from now on I will consider all the usability problems as high priority

**Comment by simonbcn** [comment]
I would like to help you but I don't know that programming language.

**Comment by v0idpwn** [comment]
I'm calling on this one. Will do it at the weekend

**Comment by yatima1460** [comment]
Done, binaries will be published soon

**Comment by yatima1460** [comment]
Binaries published
