### ISSUE TITLE
Right click should show a contextual menu with "Open containing folder"

### ISSUE THREAD

**Issue by yatima1460** [yatima1460/Drill#47]
- Open
- Open with...
- Open containing folder
- Copy file name
- Copy full path
- Copy date

**Comment by v0idpwn** [comment]
Will be working on this

{if I manage to finish my sprint}

**Comment by v0idpwn** [comment]
Forgive me for I have sinned

**Comment by yatima1460** [comment]
You mean GTK devs have sinned

**Comment by yatima1460** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Right click contextual menu](https://trello.com/c/utjBp1ar/9-right-click-contextual-menu)

**Comment by yatima1460** [comment]
https://github.com/yatima1460/Drill/releases/tag/v566
