### ISSUE TITLE
Building 

### ISSUE THREAD

**Issue by dedobbin** [yatima1460/Drill#48]
When using DMD (Ubuntu 18.04.2 LTS) and following build instructions i run into following errors:

```
/usr/include/dmd/phobos/std/algorithm.d(12775,54): Error: variable range1 cannot be read at compile time
/usr/include/dmd/phobos/std/algorithm.d(12775,60):        called from here: save(range1)
/usr/include/dmd/phobos/std/algorithm.d(12775,53):        called from here: zip(save(range1), repeat(a))
/usr/include/dmd/phobos/std/algorithm.d(514,19):        called from here: delegate (Tuple!(string, string, string) a) => zip(save(range1), repeat(a))(this._input.front())
/usr/include/dmd/phobos/std/algorithm.d-mixin-3742(3745,20):        called from here: this._items.front()
/usr/include/dmd/phobos/std/algorithm.d(509,24):        called from here: this._input.popFront()
/usr/include/dmd/phobos/std/algorithm.d(509,24):        called from here: this._input.popFront()
/usr/include/dmd/phobos/std/algorithm.d(3741,32):        called from here: this._items.popFront()
/usr/include/dmd/phobos/std/algorithm.d(509,24):        called from here: this._input.popFront()
/usr/include/dmd/phobos/std/algorithm.d(509,24):        called from here: this._input.popFront()
/usr/include/dmd/phobos/std/array.d(35,9):        called from here: __r29.popFront()
/home/dozer/.dub/packages/datefmt-1.0.3/datefmt/source/datefmt.d(236,9):        called from here: array(map(cartesianProduct(["%a, ", "%A, ", ""], ["%d "], ["%b", "%B"], [" %Y %H:%M:%S "], ["%Z", "%z", "%.%.%.", "%.%.", "%."])))
```

**Comment by yatima1460** [comment]
Two things:
1. Are you sure you are not using GDC as backend compiler? (Don't install dub using apt)
2. master is the only branch in which I dump everything, try to build a tag marked as release like https://github.com/yatima1460/Drill/tree/1.245

**Comment by yatima1460** [comment]
If it still fails even after building a release tag it could be because you have a 32-bit system or an older version of dmd

**Comment by yatima1460** [comment]
Also this calls for the idea of using a develop branch

**Comment by dedobbin** [comment]
Ok, i tried a stable version (tag you mentioned, 1.245) but i got same result

**Comment by yatima1460** [comment]
Can you post your DMD version?

**Comment by yatima1460** [comment]
Also it crashes not because of Drill, but because of datefmt, a library I use 🤔

**Comment by dedobbin** [comment]
Okok. ill mess around with it some more, but seeing how it's external/can't fix, i guess this can be closed?

**Comment by yatima1460** [comment]
Nono, I want to help you, how can I not help a guy with an Ace Attorney profile pic?

But it's pretty strange that it doesn't build on Ubuntu when both Travis and I use a Debian derivative to build it.

try this:


```bash
wget http://downloads.dlang.org/releases/2.x/2.086.0/dmd.2.086.0.linux.tar.xz
7z x dmd.2.086.0.linux.tar.xz
7z x dmd.2.086.0.linux.tar
export DUB="$PWD"/dmd2/linux/bin64/dub
chmod +x $DUB
chmod +x "$PWD"/dmd2/linux/bin64/dmd
cd Source/Frontend/GTK
$DUB build -b release --arch=x86_64 --parallel
```

**Comment by yatima1460** [comment]
if you get the same error then I am 90% sure it's your system setup that has problems, maybe you have a wrong phobos lib installed or something

**Comment by dedobbin** [comment]
Hey, sorry was a bit busy last couple of days, hope i have some time this week. thanks for the help

**Comment by dedobbin** [comment]
Yes, that the trick !
