### ISSUE TITLE
DEB package depends on libgio-2.0, which is not in Ubuntu (2.0.0)

### ISSUE THREAD

**Issue by logix2** [yatima1460/Drill#52]
Using Ubuntu 19.04, trying to install Drill 2.0.0, it has unmet dependencies, depending on libgio-2.0, which is not in Ubuntu:

```
$ sudo apt install ./Drill-GTK-linux-x86_64-release-2.0.0.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'drill-search-gtk' instead of './Drill-GTK-linux-x86_64-release-2.0.0.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 drill-search-gtk : Depends: libgio-2.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

This does not happen with the stable version that can be downloaded from https://drill.software/ .

**Comment by yatima1460** [comment]
@logix2 Amazing, you guys don't give me time to check the new version! 😄
I would have tested the beta .deb today on Debian

And then marked it Release manually if it worked correctly

One second I will fix this today or tomorrow

**Comment by yatima1460** [comment]
https://github.com/yatima1460/Drill/releases/tag/2.0.0
